// Generated by Wrangler on Sat Nov 09 2024 17:27:17 GMT+0700 (Indochina Time)
// by running `wrangler types`

interface Env {
	KV: KVNamespace;
	NOTION_API_KEY: string;
	NOTION_TASKS_DATABASE_ID: string;
	NOTION_COURSES_DATABASE_ID: string;
	NOTION_NOTES_DATABASE_ID: string;
	GOOGLE_CALENDAR_ID: string;
	GOOGLE_APP_CLIENT_ID: string;
	GOOGLE_APP_SECRET: string;
	GOOGLE_REDIRECT_URI: string;
	GOOGLE_SERVICE_ACCOUNT_KEY: string;
}
